name: Metrics
on:
  schedule: [{cron: "0 6 * * *"}] # Запуск каждое утро
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Настройки вывода
          filename: github-metrics.svg
          base: "" # Скрываем стандартную шапку, чтобы оставить только плагины
          
          # 1. Изометрический календарь
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # 2. Достижения (Achievements)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C # Показывает достижения выше уровня C
          
          # 3. Топ языков (Languages)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes # Анализировать код глубже
          
          # 4. Строки кода (Lines of code)
          plugin_lines: yes
